import fs from 'fs';
import os from 'os';
import path from 'path';

import {
  isEncryptedZip,
  ENCRYPTABLE_ARCHIVE_EXTS,
} from '../../../src/services/file-archive-service';

/**
 * A `.7z` built by another project was emailed AES-encrypted
 * (`Method = LZMA2:24 7zAES`) and the recipient could not open it: Windows 11's
 * built-in extractor refuses encrypted archives outright. claudito passed it
 * through untouched because `.7z` was on the "already an archive" list, so the
 * zip path was skipped entirely.
 *
 * The blocker is the encryption, not the container — an encrypted zip fails the
 * same way — and wrapping does not help, because the encrypted member survives
 * inside the wrapper. So these are refused, and the fix goes in the message.
 */
describe('archive encryption guard', () => {
  let dir: string;

  beforeEach(() => {
    dir = fs.mkdtempSync(path.join(os.tmpdir(), 'archive-guard-'));
  });

  afterEach(() => {
    fs.rmSync(dir, { recursive: true, force: true });
  });

  /**
   * Hand-built local file header. Deterministic and needs no 7-Zip on the box,
   * which a fixture generated by an external binary would.
   */
  function writeZip(name: string, flags: number): string {
    const header = Buffer.alloc(30);
    header.writeUInt32LE(0x04034b50, 0); // local file header signature
    header.writeUInt16LE(20, 4); // version needed
    header.writeUInt16LE(flags, 6); // general purpose bit flag
    header.writeUInt16LE(8, 8); // deflate

    const file = path.join(dir, name);
    fs.writeFileSync(file, header);
    return file;
  }

  describe('isEncryptedZip', () => {
    it('reports a plain zip as not encrypted', () => {
      expect(isEncryptedZip(writeZip('plain.zip', 0))).toBe(false);
    });

    it('detects the encrypted bit', () => {
      // Bit 0 of the general purpose bit flag. This is the case an extension
      // check cannot catch: a .zip just as unopenable as the .7z.
      expect(isEncryptedZip(writeZip('secret.zip', 0x0001))).toBe(true);
    });

    it('ignores other flag bits', () => {
      // 0x0008 is the data-descriptor bit, which archiver sets routinely.
      expect(isEncryptedZip(writeZip('streamed.zip', 0x0008))).toBe(false);
    });

    it('detects encryption alongside other flags', () => {
      expect(isEncryptedZip(writeZip('both.zip', 0x0009))).toBe(true);
    });

    it('treats a non-zip as not encrypted', () => {
      const file = path.join(dir, 'notes.txt');
      fs.writeFileSync(file, 'not a zip at all, but long enough to read');

      expect(isEncryptedZip(file)).toBe(false);
    });

    it('treats an empty archive as not encrypted', () => {
      // An empty zip starts with the end-of-central-directory record, not a
      // local file header, and has nothing to encrypt.
      const eocd = Buffer.alloc(22);
      eocd.writeUInt32LE(0x06054b50, 0);
      const file = path.join(dir, 'empty.zip');
      fs.writeFileSync(file, eocd);

      expect(isEncryptedZip(file)).toBe(false);
    });

    it('does not throw on a missing file', () => {
      // Unreadable is not "encrypted" — createZipArchive reports missing paths
      // through its own `skipped` list, and throwing here would turn a reportable
      // mistake into a failed send.
      expect(() => isEncryptedZip(path.join(dir, 'nope.zip'))).not.toThrow();
      expect(isEncryptedZip(path.join(dir, 'nope.zip'))).toBe(false);
    });

    it('does not throw on a file shorter than a header', () => {
      const file = path.join(dir, 'tiny.zip');
      fs.writeFileSync(file, Buffer.from([0x50, 0x4b]));

      expect(isEncryptedZip(file)).toBe(false);
    });

    it('does not throw on a directory', () => {
      expect(isEncryptedZip(dir)).toBe(false);
    });
  });

  describe('ENCRYPTABLE_ARCHIVE_EXTS', () => {
    it('covers the formats that reached a recipient unopenable', () => {
      expect(ENCRYPTABLE_ARCHIVE_EXTS.has('.7z')).toBe(true);
      expect(ENCRYPTABLE_ARCHIVE_EXTS.has('.rar')).toBe(true);
    });

    it('does not block zip, which is the format we want everything sent as', () => {
      // Blocking .zip would refuse the one archive that works. Encrypted zips
      // are caught by isEncryptedZip instead, on content rather than name.
      expect(ENCRYPTABLE_ARCHIVE_EXTS.has('.zip')).toBe(false);
    });

    it('does not block tar/gz, which carry no password support', () => {
      for (const ext of ['.tar', '.gz', '.tgz']) {
        expect(ENCRYPTABLE_ARCHIVE_EXTS.has(ext)).toBe(false);
      }
    });
  });
});
